### ISSUE TITLE
demo crashes on line 187 because ft_face.glyph is nil

### ISSUE THREAD

**Issue by pJotoro** [englerj/odin-freetype#4]

**Comment by englerj** [comment]
I took a short look at this tonight but wasn't able to reproduce it. Are you running the demo from the demo directory? My only other guess thus far is that one of the freetype procedures is failing. I've added in some asserts to the demo, try running it again with the `-debug` switch and see if you hit one of the asserts and, if so, see if the error value can provide some insight.

**Comment by pJotoro** [comment]
Oh, I tried using -file and now it works.
